// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: questionsandanswers.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "questionsandanswers.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace SERQuestions {

namespace {

const ::google::protobuf::Descriptor* Question_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Question_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_questionsandanswers_2eproto() {
  protobuf_AddDesc_questionsandanswers_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "questionsandanswers.proto");
  GOOGLE_CHECK(file != NULL);
  Question_descriptor_ = file->message_type(0);
  static const int Question_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Question, questiontext_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Question, answers_),
  };
  Question_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Question_descriptor_,
      Question::default_instance_,
      Question_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Question, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Question, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Question));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_questionsandanswers_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Question_descriptor_, &Question::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_questionsandanswers_2eproto() {
  delete Question::default_instance_;
  delete Question_reflection_;
}

void protobuf_AddDesc_questionsandanswers_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\031questionsandanswers.proto\022\014SERQuestion"
    "s\"1\n\010Question\022\024\n\014questionText\030\001 \002(\t\022\017\n\007a"
    "nswers\030\002 \003(\t", 92);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "questionsandanswers.proto", &protobuf_RegisterTypes);
  Question::default_instance_ = new Question();
  Question::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_questionsandanswers_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_questionsandanswers_2eproto {
  StaticDescriptorInitializer_questionsandanswers_2eproto() {
    protobuf_AddDesc_questionsandanswers_2eproto();
  }
} static_descriptor_initializer_questionsandanswers_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Question::kQuestionTextFieldNumber;
const int Question::kAnswersFieldNumber;
#endif  // !_MSC_VER

Question::Question()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:SERQuestions.Question)
}

void Question::InitAsDefaultInstance() {
}

Question::Question(const Question& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:SERQuestions.Question)
}

void Question::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  questiontext_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Question::~Question() {
  // @@protoc_insertion_point(destructor:SERQuestions.Question)
  SharedDtor();
}

void Question::SharedDtor() {
  if (questiontext_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete questiontext_;
  }
  if (this != default_instance_) {
  }
}

void Question::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Question::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Question_descriptor_;
}

const Question& Question::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_questionsandanswers_2eproto();
  return *default_instance_;
}

Question* Question::default_instance_ = NULL;

Question* Question::New() const {
  return new Question;
}

void Question::Clear() {
  if (has_questiontext()) {
    if (questiontext_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
      questiontext_->clear();
    }
  }
  answers_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Question::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SERQuestions.Question)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string questionText = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_questiontext()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->questiontext().data(), this->questiontext().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "questiontext");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_answers;
        break;
      }

      // repeated string answers = 2;
      case 2: {
        if (tag == 18) {
         parse_answers:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_answers()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->answers(this->answers_size() - 1).data(),
            this->answers(this->answers_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "answers");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_answers;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SERQuestions.Question)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SERQuestions.Question)
  return false;
#undef DO_
}

void Question::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SERQuestions.Question)
  // required string questionText = 1;
  if (has_questiontext()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->questiontext().data(), this->questiontext().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "questiontext");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->questiontext(), output);
  }

  // repeated string answers = 2;
  for (int i = 0; i < this->answers_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
    this->answers(i).data(), this->answers(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE,
    "answers");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->answers(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:SERQuestions.Question)
}

::google::protobuf::uint8* Question::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SERQuestions.Question)
  // required string questionText = 1;
  if (has_questiontext()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->questiontext().data(), this->questiontext().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "questiontext");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->questiontext(), target);
  }

  // repeated string answers = 2;
  for (int i = 0; i < this->answers_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->answers(i).data(), this->answers(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "answers");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->answers(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SERQuestions.Question)
  return target;
}

int Question::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string questionText = 1;
    if (has_questiontext()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->questiontext());
    }

  }
  // repeated string answers = 2;
  total_size += 1 * this->answers_size();
  for (int i = 0; i < this->answers_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->answers(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Question::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Question* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Question*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Question::MergeFrom(const Question& from) {
  GOOGLE_CHECK_NE(&from, this);
  answers_.MergeFrom(from.answers_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_questiontext()) {
      set_questiontext(from.questiontext());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Question::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Question::CopyFrom(const Question& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Question::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void Question::Swap(Question* other) {
  if (other != this) {
    std::swap(questiontext_, other->questiontext_);
    answers_.Swap(&other->answers_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Question::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Question_descriptor_;
  metadata.reflection = Question_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace SERQuestions

// @@protoc_insertion_point(global_scope)
